services:
  web-app:
    build: ./web-app
    container_name: portfolio-web
    restart: always
    ports:
      - "5000:5000" 
    environment:
      - COUNTER_API_URL=http://counter-app:5000/api/count
      - FLASK_DEBUG=True
    volumes:
      - ./web-app:/app
    depends_on:
      - counter-app
    networks:
      - portfolio-network

  counter-app:
    build: ./counter-app
    container_name: portfolio-counter
    restart: always
    ports:
      - "5001:5000" 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_DEBUG=True
    volumes:
      - ./counter-app:/app
    depends_on:
      - redis
    networks:
      - portfolio-network

  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  redis-data: