name: Deploy Function App

on:
  push:
    branches:
      - main
    paths:
      - function/**
env:
  AZURE_FUNCTIONAPP_NAME: 'func-cloudresume-prd'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'function'       

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}