name: Deploy Frontend

permissions:
  id-token: write

# Trigger
on:
  push:
    branches:
      - main
    paths:
      - index.html

# Jobs
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       path: ./site

    # Update Last Update
    - name: Update last updated date
      shell: pwsh
      run: 
        (Get-Content ./site/index.html).Replace('_lastupdate_',$(Get-Date -Format 'dd/MM/yyyy')) | Set-Content ./site/index.html

    # Login To Azure
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.BACKEND_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.BACKEND_AZURE_SUBSCRIPTION_ID }}

    # Clear Storage Account
    - name: 'Empty the web container'
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob delete-batch --account-name  ${{ secrets.SITE_STORAGE_ACCOUNT_NAME }} --source \$web --auth-mode login

    # Deploy to the Azure Storage Account
    - name: 'Deploy to Azure Storage'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -s ./site -d \$web --account-name  ${{ secrets.SITE_STORAGE_ACCOUNT_NAME }} --auth-mode login
