name: Build & Push Container App Docker Image

on: 
  push:
    branches:
     - main
     - dev
    paths:
      - 'app/web-app/**'
  workflow_dispatch:
    
env:
  IMAGE_NAME: 'resume/frontend'

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # Log in to Azure Container Registry using docker login
    - name: Login to ACR via Docker
      run: |
        echo ${{ secrets.ACR_SPC_USER_SECRET }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_SPC_USER_NAME }} --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: |
        date=$(date '+%Y%m%d')
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$date app/web-app

    # Push Docker image to ACR
    - name: Push Docker image
      run: |
        date=$(date '+%Y%m%d')
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$date
        docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$date ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest